export const countryToIso2: Record<string, string> = {
  "Andorra": "AD",
  "United Arab Emirates": "AE",
  "Afghanistan": "AF",
  "Antigua and Barbuda": "AG",
  "Anguilla": "AI",
  "Albania": "AL",
  "Armenia": "AM",
  "Angola": "AO",
  "Antarctica": "AQ",
  "Argentina": "AR",
  "American Samoa": "AS",
  "Austria": "AT",
  "Australia": "AU",
  "Aruba": "AW",
  "Åland Islands": "AX",
  "Azerbaijan": "AZ",
  "Bosnia & Herzegovina": "BA",
  "Barbados": "BB",
  "Bangladesh": "BD",
  "Belgium": "BE",
  "Burkina Faso": "BF",
  "Bulgaria": "BG",
  "Bahrain": "BH",
  "Burundi": "BI",
  "Benin": "BJ",
  "Saint Barthélemy": "BL",
  "Bermuda": "BM",
  "Brunei Darussalam": "BN",
  "Bolivia, Plurinational State of": "BO",
  "Bonaire, Sint Eustatius and Saba": "BQ",
  "Brazil": "BR",
  "Bahamas": "BS",
  "Bhutan": "BT",
  "Bouvet Island": "BV",
  "Botswana": "BW",
  "Belarus": "BY",
  "Belize": "BZ",
  "Canada": "CA",
  "Cocos (Keeling) Islands": "CC",
  "DR Congo": "CD",
  "Central African Republic": "CF",
  "Congo": "CG",
  "Switzerland": "CH",
  "Ivory Coast": "CI",
  "Cook Islands": "CK",
  "Chile": "CL",
  "Cameroon": "CM",
  "China": "CN",
  "Colombia": "CO",
  "Costa Rica": "CR",
  "Cuba": "CU",
  "Cape Verde": "CV",
  "Curaçao": "CW",
  "Christmas Island": "CX",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Germany": "DE",
  "Djibouti": "DJ",
  "Denmark": "DK",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Algeria": "DZ",
  "Ecuador": "EC",
  "Estonia": "EE",
  "Egypt": "EG",
  "Western Sahara": "EH",
  "Eritrea": "ER",
  "Spain": "ES",
  "Ethiopia": "ET",
  "Finland": "FI",
  "Fiji": "FJ",
  "Falkland Islands (Malvinas)": "FK",
  "Micronesia, Federated States of": "FM",
  "Faroe Islands": "FO",
  "France": "FR",
  "Gabon": "GA",
  "England": "GB-ENG",
  "Grenada": "GD",
  "Georgia": "GE",
  "French Guiana": "GF",
  "Guernsey": "GG",
  "Ghana": "GH",
  "Gibraltar": "GI",
  "Greenland": "GL",
  "Gambia": "GM",
  "Guinea": "GN",
  "Guadeloupe": "GP",
  "Equatorial Guinea": "GQ",
  "Greece": "GR",
  "South Georgia and the South Sandwich Islands": "GS",
  "Guatemala": "GT",
  "Guam": "GU",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Hong Kong": "HK",
  "Heard Island and McDonald Islands": "HM",
  "Honduras": "HN",
  "Croatia": "HR",
  "Haiti": "HT",
  "Hungary": "HU",
  "Indonesia": "ID",
  "Ireland": "IE",
  "Israel": "IL",
  "Isle of Man": "IM",
  "India": "IN",
  "British Indian Ocean Territory": "IO",
  "Iraq": "IQ",
  "Iran": "IR",
  "Iceland": "IS",
  "Italy": "IT",
  "Jersey": "JE",
  "Jamaica": "JM",
  "Jordan": "JO",
  "Japan": "JP",
  "Kenya": "KE",
  "Kyrgyzstan": "KG",
  "Cambodia": "KH",
  "Kiribati": "KI",
  "Comoros": "KM",
  "Saint Kitts and Nevis": "KN",
  "Korea, Democratic People's Republic of": "KP",
  "Kuwait": "KW",
  "Cayman Islands": "KY",
  "Kazakhstan": "KZ",
  "Lao People's Democratic Republic": "LA",
  "Lebanon": "LB",
  "Saint Lucia": "LC",
  "Liechtenstein": "LI",
  "Sri Lanka": "LK",
  "Liberia": "LR",
  "Lesotho": "LS",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Latvia": "LV",
  "Libya": "LY",
  "Morocco": "MA",
  "Monaco": "MC",
  "Moldova, Republic of": "MD",
  "Montenegro": "ME",
  "Saint Martin (French part)": "MF",
  "Madagascar": "MG",
  "Marshall Islands": "MH",
  "North Macedonia": "MK",
  "Mali": "ML",
  "Myanmar": "MM",
  "Mongolia": "MN",
  "Macao": "MO",
  "Northern Mariana Islands": "MP",
  "Martinique": "MQ",
  "Mauritania": "MR",
  "Montserrat": "MS",
  "Malta": "MT",
  "Mauritius": "MU",
  "Maldives": "MV",
  "Malawi": "MW",
  "Mexico": "MX",
  "Malaysia": "MY",
  "Mozambique": "MZ",
  "Namibia": "NA",
  "New Caledonia": "NC",
  "Niger": "NE",
  "Norfolk Island": "NF",
  "Nigeria": "NG",
  "Nicaragua": "NI",
  "Netherlands": "NL",
  "Norway": "NO",
  "Nepal": "NP",
  "Nauru": "NR",
  "Niue": "NU",
  "New Zealand": "NZ",
  "Oman": "OM",
  "Panama": "PA",
  "Peru": "PE",
  "French Polynesia": "PF",
  "Papua New Guinea": "PG",
  "Philippines": "PH",
  "Pakistan": "PK",
  "Poland": "PL",
  "Saint Pierre and Miquelon": "PM",
  "Pitcairn": "PN",
  "Puerto Rico": "PR",
  "Palestine, State of": "PS",
  "Portugal": "PT",
  "Palau": "PW",
  "Paraguay": "PY",
  "Qatar": "QA",
  "Réunion": "RE",
  "Romania": "RO",
  "Serbia": "RS",
  "Russia": "RU",
  "Rwanda": "RW",
  "Saudi Arabia": "SA",
  "Scotland": "GB-SCT",
  "Solomon Islands": "SB",
  "Seychelles": "SC",
  "Sudan": "SD",
  "Sweden": "SE",
  "Singapore": "SG",
  "Saint Helena, Ascension and Tristan da Cunha": "SH",
  "Slovenia": "SI",
  "Svalbard and Jan Mayen": "SJ",
  "Slovakia": "SK",
  "Sierra Leone": "SL",
  "San Marino": "SM",
  "Senegal": "SN",
  "Somalia": "SO",
  "Suriname": "SR",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Sao Tome and Principe": "ST",
  "El Salvador": "SV",
  "Sint Maarten (Dutch part)": "SX",
  "Syrian Arab Republic": "SY",
  "Eswatini": "SZ",
  "Turks and Caicos Islands": "TC",
  "Chad": "TD",
  "French Southern Territories": "TF",
  "Togo": "TG",
  "Thailand": "TH",
  "Tajikistan": "TJ",
  "Tokelau": "TK",
  "Timor-Leste": "TL",
  "Turkmenistan": "TM",
  "Tunisia": "TN",
  "Tonga": "TO",
  "Turkey": "TR",
  "Trinidad and Tobago": "TT",
  "Tuvalu": "TV",
  "Taiwan, Province of China": "TW",
  "Tanzania, United Republic of": "TZ",
  "Ukraine": "UA",
  "Uganda": "UG",
  "United States Minor Outlying Islands": "UM",
  "United States": "US",
  "Uruguay": "UY",
  "USA": "US",
  "Uzbekistan": "UZ",
  "Holy See": "VA",
  "Saint Vincent and the Grenadines": "VC",
  "Venezuela, Bolivarian Republic of": "VE",
  "Virgin Islands (British)": "VG",
  "Virgin Islands (U.S.)": "VI",
  "Viet Nam": "VN",
  "Vanuatu": "VU",
  "Wallis and Futuna": "WF",
  "Wales": "GB-WLS",
  "Samoa": "WS",
  "Yemen": "YE",
  "Mayotte": "YT",
  "South Africa": "ZA",
  "Zambia": "ZM",
  "Zimbabwe": "ZW"
};

export const iso3ToIso2: Record<string, string> = {
  BGD: "BD",
  BEL: "BE",
  BFA: "BF",
  BGR: "BG",
  BIH: "BA",
  BRB: "BB",
  WLF: "WF",
  BLM: "BL",
  BMU: "BM",
  BRN: "BN",
  BOL: "BO",
  BHR: "BH",
  BDI: "BI",
  BEN: "BJ",
  BTN: "BT",
  JAM: "JM",
  BVT: "BV",
  BWA: "BW",
  WSM: "WS",
  BES: "BQ",
  BRA: "BR",
  BHS: "BS",
  JEY: "JE",
  BLR: "BY",
  BLZ: "BZ",
  RUS: "RU",
  RWA: "RW",
  SRB: "RS",
  TLS: "TL",
  REU: "RE",
  TKM: "TM",
  TJK: "TJ",
  ROU: "RO",
  TKL: "TK",
  GNB: "GW",
  GUM: "GU",
  GTM: "GT",
  SGS: "GS",
  GRC: "GR",
  GNQ: "GQ",
  GLP: "GP",
  JPN: "JP",
  GUY: "GY",
  GGY: "GG",
  GUF: "GF",
  GEO: "GE",
  GRD: "GD",
  GBR: "GB",
  GAB: "GA",
  SLV: "SV",
  GIN: "GN",
  GMB: "GM",
  GRL: "GL",
  GIB: "GI",
  GHA: "GH",
  OMN: "OM",
  TUN: "TN",
  JOR: "JO",
  HRV: "HR",
  HTI: "HT",
  HUN: "HU",
  HKG: "HK",
  HND: "HN",
  HMD: "HM",
  VEN: "VE",
  PRI: "PR",
  PSE: "PS",
  PLW: "PW",
  PRT: "PT",
  SJM: "SJ",
  PRY: "PY",
  IRQ: "IQ",
  PAN: "PA",
  PYF: "PF",
  PNG: "PG",
  PER: "PE",
  PAK: "PK",
  PHL: "PH",
  PCN: "PN",
  POL: "PL",
  SPM: "PM",
  ZMB: "ZM",
  ESH: "EH",
  EST: "EE",
  EGY: "EG",
  ZAF: "ZA",
  ECU: "EC",
  ITA: "IT",
  VNM: "VN",
  SLB: "SB",
  ETH: "ET",
  SOM: "SO",
  ZWE: "ZW",
  SAU: "SA",
  ESP: "ES",
  ERI: "ER",
  MNE: "ME",
  MDA: "MD",
  MDG: "MG",
  MAF: "MF",
  MAR: "MA",
  MCO: "MC",
  UZB: "UZ",
  MMR: "MM",
  MLI: "ML",
  MAC: "MO",
  MNG: "MN",
  MHL: "MH",
  MKD: "MK",
  MUS: "MU",
  MLT: "MT",
  MWI: "MW",
  MDV: "MV",
  MTQ: "MQ",
  MNP: "MP",
  MSR: "MS",
  MRT: "MR",
  IMN: "IM",
  UGA: "UG",
  TZA: "TZ",
  MYS: "MY",
  MEX: "MX",
  ISR: "IL",
  FRA: "FR",
  IOT: "IO",
  SHN: "SH",
  FIN: "FI",
  FJI: "FJ",
  FLK: "FK",
  FSM: "FM",
  FRO: "FO",
  NIC: "NI",
  NLD: "NL",
  NOR: "NO",
  NAM: "NA",
  VUT: "VU",
  NCL: "NC",
  NER: "NE",
  NFK: "NF",
  NGA: "NG",
  NZL: "NZ",
  NPL: "NP",
  NRU: "NR",
  NIU: "NU",
  COK: "CK",
  XKX: "XK",
  CIV: "CI",
  CHE: "CH",
  COL: "CO",
  CHN: "CN",
  CMR: "CM",
  CHL: "CL",
  CCK: "CC",
  CAN: "CA",
  COG: "CG",
  CAF: "CF",
  COD: "CD",
  CZE: "CZ",
  CYP: "CY",
  CXR: "CX",
  CRI: "CR",
  CUW: "CW",
  CPV: "CV",
  CUB: "CU",
  SWZ: "SZ",
  SYR: "SY",
  SXM: "SX",
  KGZ: "KG",
  KEN: "KE",
  SSD: "SS",
  SUR: "SR",
  KIR: "KI",
  KHM: "KH",
  KNA: "KN",
  COM: "KM",
  STP: "ST",
  SVK: "SK",
  KOR: "KR",
  SVN: "SI",
  PRK: "KP",
  KWT: "KW",
  SEN: "SN",
  SMR: "SM",
  SLE: "SL",
  SYC: "SC",
  KAZ: "KZ",
  CYM: "KY",
  SGP: "SG",
  SWE: "SE",
  SDN: "SD",
  DOM: "DO",
  DMA: "DM",
  DJI: "DJ",
  DNK: "DK",
  VGB: "VG",
  DEU: "DE",
  YEM: "YE",
  DZA: "DZ",
  USA: "US",
  URY: "UY",
  MYT: "YT",
  UMI: "UM",
  LBN: "LB",
  LCA: "LC",
  LAO: "LA",
  TUV: "TV",
  TWN: "TW",
  TTO: "TT",
  TUR: "TR",
  LKA: "LK",
  LIE: "LI",
  LVA: "LV",
  TON: "TO",
  LTU: "LT",
  LUX: "LU",
  LBR: "LR",
  LSO: "LS",
  THA: "TH",
  ATF: "TF",
  TGO: "TG",
  TCD: "TD",
  TCA: "TC",
  LBY: "LY",
  VAT: "VA",
  VCT: "VC",
  ARE: "AE",
  AND: "AD",
  ATG: "AG",
  AFG: "AF",
  AIA: "AI",
  VIR: "VI",
  ISL: "IS",
  IRN: "IR",
  ARM: "AM",
  ALB: "AL",
  AGO: "AO",
  ATA: "AQ",
  ASM: "AS",
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  ABW: "AW",
  IND: "IN",
  ALA: "AX",
  AZE: "AZ",
  IRL: "IE",
  IDN: "ID",
  UKR: "UA",
  QAT: "QA",
  MOZ: "MZ",
  SUI: "CH",
  WAL: "GB-WLS",
  DEN: "DK",
  NED: "NL",
  ENG: "GB-ENG",
  CRO: "HR",
  SCO: "GB-SCT",
  POR: "PT",
  GER: "DE",
  CHI: "CL",
  URU: "UY",
  PAR: "PY",
  CRC: "CR",
  KSA: "SA",
  GRE: "GR",
  ALG: "DZ",
};
